### PR TITLE
Create Flippando.md

### PR DESCRIPTION
**Pull request by irreverentsimplicity**

### CODE REVIEW

**Comment by michelleellen** [comment]
Hey @irreverentsimplicity 

Thanks for submitting, we will take a look and come back with follow up questions shortly. We will be doing reviews in batches.

**Comment by michelleellen** [comment]
Hey @irreverentsimplicity - how about today a 3:30 to review?

**Comment by michelleellen** [comment]
We are looking forward to working with you on Flippando 😊

**Comment by jaekwon** [comment]
any game that has some popularity already proven on ethereum sounds like a good one to port.

**Comment by michelleellen** [comment]
Update: Grant approved for work on porting Flipanndo to Gno.land from August to December 2023.

**Pull request merged**
