### PR TITLE
Blockdudes - Multisig Infra

### PR DESCRIPTION
**Pull request by amritkumarj**
**What We'll Build:** Multisig infrastructure on GnoLand

**Cool Features:** Easy account creation, asset management, custom message handling, and more.

**Grant:** We're asking for $40,000. No upfront cash needed.

**When Will It Be Done?:** Roughly 2 months.

### CODE REVIEW

**Comment by michelleellen** [comment]
Hi @amritkumarj 

Thanks for your submission, we'll take a look and review in our next session in September. 

We'll come back soon if we have additional questions that need answering or to set up a call. 

Thanks!

**Comment by michelleellen** [comment]
Hi @amritkumarj 

A small update, the reviews will start again in mid October. Thanks for your submission, stay tuned!

**Comment by jaekwon** [comment]
We already have multisig support at the base layer, FYI, so it might be more interesting to explore other ideas around money management (even though it does make sense to also support flexible authorization mechanisms on the smart contract layer).

**Comment by jaekwon** [comment]
How about a wallet contract that can handle throttling/controls?

For example I would want to use a smart contract that holds funds, and I'd like to give my devices (like sessions) access to these funds but limited in some way, like only Xgnot/day.

Perhaps there is a notion of sub-accounts, like having multiple accounts in a bank; and maybe it is fast to transfer funds from one account to another (with sufficient privileges), and each subaccount has different additional access keys. For example one could use this to manage a expense reimbursement function. Every "employee" can have a certain credit limit, and the "employer/owner" has complete control otherwise.

**Comment by amritkumarj** [comment]
Your idea sounds great, this is the type of multi-sig I can imagine.

Both for Companies and personal use - where users can interact with it on any blockchain: receive and send money, interact with defi application from all blockchains from a single DAPP on gno land

image

image

**Comment by michelleellen** [comment]
Hi @amritkumarj I have followed up via email.

**Comment by michelleellen** [comment]
Hey @amritkumarj nice contribution thank you! https://github.com/gnolang/gno/pull/1502 - I reached out to follow up.

**Comment by amritkumarj** [comment]
Hey @michelleellen replied to your email please check, thanks!

**Comment by michelleellen** [comment]
Thanks @amritkumarj I see your new grant submission based on feedback. Since this one was not in the current scope of our grants, we will add it to the archive folder.

**Pull request closed without merging**
