### PR TITLE
Add pixel beans.

### PR DESCRIPTION
**Pull request by xbdyhh**

### CODE REVIEW

**Comment by xbdyhh** [comment]
@michelleellen

**Comment by michelleellen** [comment]
Thank you! We will review internally initially and come back with questions or a follow up call. This will take about 2 weeks.

**Comment by ArtecFusion** [comment]
Hi @michelleellen We want to show you something, we're done with the [Alpha](https://www.pixelbeans.xyz/).

**Comment by michelleellen** [comment]
Hey @xbdyhh thanks for sharing this update, we will take a look at the alpha. We've had a few questions after a look internally:

Will Pixel Beans provide something reusable for other gno developers, for example in the sense of a libraries?
Can you expand on the technical challenges Pixel Beans is solving in terms of NFT development?

**Comment by xbdyhh** [comment]
@michelleellen   We are not an infrastructure project, but we focus on nft on the whole chain, and optimize the storage space of nft on the chain, so I think, in the future, we can integrate our nft library for future developers to use

**Comment by xbdyhh** [comment]
At the same time, we also have plans to combine nft and blockchain games in the future

**Comment by ArtecFusion** [comment]
@michelleellen We have a more detailed answer to your question, please check back.


Challenges Encountered in PixelBeans' Current Development Phase

PixelBeans is the NFT project with the largest total to date with a total of 16^6 = 16,777,216 unique items. Our first major challenge lies in effectively integrating and managing this vast quantity of NFT images. While we initially attempted to store these NFT images using IPFS, we faced issues due to the significant size of the generated SVG data. Despite each SVG image being just 24 KB in size, the cumulative data reached a staggering 384 GB. The corresponding metajson file also reached 2.4 GB in size. IPFS struggled to handle this immense data load, resulting in slow loading speeds. Exploring an alternative path, we decided to generate SVG images directly on the blockchain through smart contracts. These images are now recognized and displayed by platforms like [OpenSea](https://testnets.opensea.io/collection/pix-8), providing a new solution for NFT image storage. We plan to offer this code as a library for NFT developers on the Gno platform.

Snipaste_2023-08-10_14-54-47

What We Can Bring to Gno

1、A fresh and innovative concept of interactive NFTs, where users can engage with PixelBeans. In the future, interactions among users will be possible, leading to various engaging gameplay possibilities.
2、We introduce a novel NFT storage approach for projects within the Gno ecosystem. Our code library can be made available to NFT developers on Gno.
3、As our project progresses, we have plans for GameFi development. While in the planning phase, our vision includes the creation of a MUD-style game centered around PixelBeans. Players can embark on adventures controlling their NFT-holding beans, interacting with on-chain data to yield different gameplay outcomes. With beans as the primary visual element, our creative possibilities are immense. We aim to fuse gaming with AI-generated art, allowing players to receive images based on their game progress. Each bean's journey will be unique, representing its distinct achievements. Such a dynamic experience was unattainable in traditional MUD games. Upon completing development, we intend to provide reusable code snippets to the Gno development community.

**Comment by ArtecFusion** [comment]
Hi @michelleellen @moul , is there any reply you can give us? What improvements do we need to make?

**Comment by michelleellen** [comment]
Hi @ArtecFusion we are working through the submission process and may need to schedule a call with you to answer some questions to see if this falls inline with what we are focusing on with the grants program at this time. Please anticipate that we get in touch sometime next week. Thanks.

**Comment by ArtecFusion** [comment]
Ok, looking forward to your reply.

**Comment by michelleellen** [comment]
Hi @xbdyhh 

We've taken the new information into account. It doesn't fit the current grant focus, but we will be looking again in mid-October with a concentration gaming, so please keep it open and we will review the status again then.

**Comment by jaekwon** [comment]
the twitter handle is dead btw https://twitter.com/PixelBeanStudio.

**Comment by ArtecFusion** [comment]
Hi @michelleellen @jaekwon 

Sorry for the late reply, we changed the name of Twitter a few days ago
Now the new one is: https://twitter.com/PixelBeansXYZ

**Comment by michelleellen** [comment]
Thanks @xbdyhh as you know at this time we won't move forward with this grant, but will add it to the archive folder to keep it referenced.

**Pull request closed without merging**
